services:
  hqms_dns:
    container_name: hqms_dns
    image: ubuntu/bind9
    ports:
      - "54:53/udp"
      - "54:53/tcp"
    volumes:
      - "disk_hqms_dns:/etc/bind"
      - "disk_hqms_dns_cache:/var/cache/bind"
      - "disk_hqms_dns_records:/var/lib/bind"
      - "disk_hqms_default:/etc/default/"
      - "./etc/resolv.conf:/etc/resolv.conf"
    networks:
        red_interna:
            ipv4_address: 192.168.2.2 #Direccion de DNS
volumes:
    disk_soluRH_dns:
    disk_soluRH_dns_cache:
    disk_soluRH_dns_records:
    disk_soluRH_default:

networks:
  red_interna:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
