# Generated by Django 5.1 on 2024-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cheque_venta",
            fields=[
                ("cheque_folio", models.AutoField(primary_key=True, serialize=False)),
                ("folio", models.IntegerField()),
                ("fecha_movimiento", models.DateField()),
                ("mesa", models.CharField(max_length=6)),
                ("factura", models.BooleanField()),
                ("total_articulos", models.IntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Tarjeta Débito", "Tarjeta Débito"),
                            ("Tarjeta Crédito", "Tarjeta Crédito"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="detalle_cheque",
            fields=[
                ("cheque_folio", models.AutoField(primary_key=True, serialize=False)),
                ("folio_det", models.IntegerField()),
                ("movimiento", models.CharField(max_length=50)),
                ("cantidad", models.IntegerField()),
                ("id_producto", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("impuesto_uno", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_sin_impuesto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
