# Generated by Django 5.0.8 on 2024-08-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cheque_venta",
            fields=[
                ("cheque_folio", models.AutoField(primary_key=True, serialize=False)),
                ("folio", models.IntegerField()),
                ("fecha_movimiento", models.DateField()),
                ("mesa", models.CharField(max_length=6)),
                ("factura", models.BooleanField()),
                ("total_articulos", models.IntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Tarjeta Débito", "Tarjeta Débito"),
                            ("Tarjeta Crédito", "Tarjeta Crédito"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bloqueado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="detalle_cheque",
            fields=[
                ("cheque_folio", models.AutoField(primary_key=True, serialize=False)),
                ("foliodet", models.IntegerField()),
                ("movimiento", models.CharField(max_length=50)),
                ("comanda", models.IntegerField()),
                ("cantidad", models.IntegerField()),
                ("idproducto", models.IntegerField()),
                ("descuento", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("impuesto1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("impuesto2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("impuesto3", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preciosinimpuestos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tiempo", models.DateTimeField()),
                ("hora", models.TimeField()),
                ("modificador", models.CharField(max_length=50)),
                ("mitad", models.BooleanField()),
                ("comentario", models.CharField(max_length=50)),
                ("idestacion", models.IntegerField()),
                ("usuariodescuento", models.CharField(max_length=50)),
                ("comentariodescuento", models.CharField(max_length=50)),
                ("idtipodescuento", models.IntegerField()),
                ("horaproduccion", models.TimeField()),
                ("idproductocompuesto", models.IntegerField()),
                ("productocompuestoprincipal", models.BooleanField()),
                (
                    "preciocatalogo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("marcar", models.BooleanField()),
                ("idmeseroproducto", models.IntegerField()),
                ("prioridadproduccion", models.IntegerField()),
                ("estatuspatin", models.BooleanField()),
                ("idcortesia", models.IntegerField()),
                ("numerotarjeta", models.CharField(max_length=50)),
                ("estadomonitor", models.BooleanField()),
                ("llavmovto", models.CharField(max_length=50)),
                ("horameserofinalizado", models.TimeField()),
                ("sistema_envio", models.IntegerField()),
                ("idturno_cierre", models.IntegerField()),
                ("procesado", models.BooleanField()),
                ("promovolumen", models.BooleanField()),
                ("iddispositivo", models.IntegerField()),
                ("productsyncidsr", models.IntegerField()),
                ("subtotalsrx", models.DecimalField(decimal_places=2, max_digits=10)),
                ("totalsrx", models.DecimalField(decimal_places=2, max_digits=10)),
                ("idmovtobillar", models.IntegerField()),
                ("idlistaprecio", models.IntegerField()),
                ("tipocambio", models.CharField(max_length=50)),
                (
                    "impuestoimporte3",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estrateca_DiscountCode", models.CharField(max_length=50)),
                ("estrateca_DiscountUID", models.CharField(max_length=50)),
                (
                    "estrateca_DiscountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("saledetailid", models.CharField(max_length=50)),
                (
                    "preciosinimpuestos_ec",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precio_ec", models.DecimalField(decimal_places=2, max_digits=10)),
                ("escargoarea", models.BooleanField()),
                ("WorkspaceId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="estados_cheque",
            fields=[
                ("cheque_folio", models.AutoField(primary_key=True, serialize=False)),
                ("bloqueado", models.BooleanField(default=False)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheques.cheque_venta",
                    ),
                ),
            ],
        ),
    ]
