# Generated by Django 5.1 on 2024-08-23 19:22

import cheques.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cheques", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="estados_cheque",
            fields=[
                ("cheque_folio", models.AutoField(primary_key=True, serialize=False)),
                (
                    "folio",
                    models.IntegerField(verbose_name=cheques.models.cheque_venta),
                ),
                ("bloqueado", models.BooleanField(default=False)),
                ("fecha_estado", models.DateField()),
            ],
        ),
    ]
