# Generated by Django 5.1 on 2024-08-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cheques", "0002_estados_cheque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estados_cheque",
            name="folio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cheques.cheque_venta"
            ),
        ),
    ]
