# Generated by Django 5.1 on 2024-08-23 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cheques", "0003_alter_estados_cheque_folio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estados_cheque",
            name="fecha_estado",
        ),
    ]
