# Generated by Django 5.1 on 2024-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheques", "0004_remove_estados_cheque_fecha_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalle_cheque",
            name="bloqueado",
            field=models.BooleanField(default=False),
        ),
    ]
