# Generated by Django 5.1 on 2024-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheques", "0005_detalle_cheque_bloqueado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalle_cheque",
            name="bloqueado",
        ),
        migrations.AddField(
            model_name="cheque_venta",
            name="bloqueado",
            field=models.BooleanField(default=False),
        ),
    ]
